# Generated by Django 6.0.1 on 2026-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectOneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedatabases',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
